Issue 32 eks managed nodegroup
defenseunicorns/iac pull request #65
Opened 2023-02-06 18:52 UTC by JaseKoonce

Adds another example that utilizes managed node groups for EKS.

2023-02-06 20:32 UTC, brianrexrode approved these changes
lgtm

2023-02-10 21:04 UTC, ntwkninja requested changes
Is it possible to leverage the same EKS module but allow switching between managed or self-managed nodegroups depending on input to one or the other?

Goal is to avoid maintaining duplicate modules where possible.

2023-02-21 17:44 UTC, brianrexrode approved these changes
send it

2023-02-21 17:44 UTC, ntwkninja approved these changes

2023-02-21 17:44 UTC, merged